//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCF_TestCode
{
    using System;
    using System.Collections.Generic;
    
    public partial class ms_storage_location1
    {
        public string location_id { get; set; }
        public string location_name { get; set; }
    }
}
